POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
content-type: application/json

{
  "description": "John 2",
  "date": "1927-10-30",
  "specialist": "doctor funk",
  "type": "Hospital",
  "discharge": {"date": "1999-09-09", "criteria": "adfafasf"}
}